# Change these first
owner: FieldControl # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Site
    url: $BARADDUR_URL
  - name: Blog
    url: $ONERING_URL
  - name: Painel de gestão
    url: $MORDOR_URL
  - name: API Principal
    url: $EYEOFSAURON_URL
  - name: API de Integração
    url: $CARCHOST_URL

status-website:
  cname: status.fieldcontrol.com.br
  logoUrl: https://fieldcontrol.com.br/assets/images/logo.svg
  name: Field Control
  introTitle: "**Field Control** Apps Status"
  introMessage: Pessoas incríveis transformando a prestação de serviços em algo incrivelmente fácil ❤︎
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
