# Change these first
owner: FieldControl # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: Site
    url: $BARADDUR_URL
    icon: https://app.fieldcontrol.com.br/favicon.ico
  - name: Blog
    url: $ONERING_URL
    icon: https://app.fieldcontrol.com.br/favicon.ico
  - name: Painel de gestão
    url: $MORDOR_URL
    icon: https://app.fieldcontrol.com.br/favicon.ico
  - name: API Principal
    url: $EYEOFSAURON_URL
  - name: API de Integração
    url: $CARCHOST_URL

status-website:
  cname: status.fieldcontrol.com.br
  logoUrl: https://app.fieldcontrol.com.br/assets/images/logos/field_logo_azul.png
  name: Field Control
  themeUrl: https://status.fieldcontrol.com.br/style.css
  introTitle: "**Field Control** Apps Status"
  introMessage: Pessoas incríveis transformando a prestação de serviços em algo incrivelmente fácil ❤︎
  metaTags:
    - name: "robots"
      content: "noindex, nofollow"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
